version: 2.1 
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
   version: 1
   build-test-and-deploy:
     jobs:
       - test #step 1
       - build:
           requires:
             - test #step 2
      #- heroku/deploy-via-git:
         #requires:
           #-build
         #filters:
           #branches:
            # only: main #step 3
#step 1
jobs:
  test:
    docker:
    - image: image:cimg/node:15.1
    steps:
      - checkout
      - run:
          name: install dependecies
          command: npm install
      - run:
          name: tests
          command: npm run test
#Step 2

  build:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          name: install dependecies
          command: npm install
      - run:
          name: build
          command: npm run build 
